In [13]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])  #2 dimensions where first has 2 elements and second has 4 elements
arr1=np.array([[[1,2,4],[3,5,6],[7,6,8]]])
arr2=np.array([[[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]]])
print(arr.shape)
print(arr1.shape)
print(arr2.shape)

(2, 4)
(1, 3, 3)
(1, 2, 3, 2)


In [15]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  #reshape
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base) 

[1 2 3 4 5 6 7 8]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
